### ISSUE TITLE
Exceptions

### ISSUE THREAD

**Issue by renatocf** [topsframework/tops#23]
Create a basic `tops::exception` and derived to be used as errors in the library.

**Comment by igorbonadio** [comment]
**Tasks:**
- [x] Create new namespace `exception`
- [x] Create base exception `tops::exception::Exception`
- [x] Create derived exception `tops::exception::NotYetImplemented`
- [x] Create derived exception `tops::exception::OutOfRange`
- [x] Create derived exception `tops::exception::InvalidModelDefinition`
