### ISSUE TITLE
Assertions

### ISSUE THREAD

**Issue by renatocf** [topsframework/tops#50]
Create assertions to test **programming**, **expensive** and **impossible** conditions inside methods.

**Comment by renatocf** [comment]
**Tasks:**
- [ ] Assert `default` case in HMM / GHMM switch-cases.
- [ ] Assert for null values in methods that return (smart / raw) pointers.
- [ ] Assert for null values in pointer that have (smart / raw) pointer parameters.

**Comment by renatocf** [comment]
**Examples:**
- Switch-case:
  
  ``` c++
  enum class Season { Spring, Summer, Fall, Winter,  };
  enum class Weather { Hot, Cold };
  
  Weather SeasonToWeather(Season season) {
    switch (season) {
      case Season::Spring: // Fall through
      case Season::Summer:
        return Weather::Hot;
      case Season::Fall:   // Fall through
      case Season::Winter:
        return Weather::Cold;
      default:
        assert("Impossible condition in switch-case");
        return {};
    }
  }
  ```
- Number range:
  
  ``` c++
  using Probability = double;
  
  inline bool is_probability(Probability prob) {
    return prob >= 0 && prob <= 1;
  }
  
  Probability drawProbability() {
    static std::mt19937 rng;
    static std::uniform_real_distribution<Probability> distribution(0.0, 1.0);
  
    auto prob = distribution(rng);
    assert(is_probability(prob));
    return prob;
  }
  ```
- Nullity:
  
  ``` c++
  template<typename T>
  inline bool not_null(const std::unique_ptr<T> &ptr) {
    return ptr != nullptr;
  }
  
  template<typename T>
  inline bool not_null(const std::shared_ptr<T> &ptr) {
    return ptr != nullptr;
  }
  
  template<typename Ptr>
  inline bool not_null(const Ptr &ptr) {
    static_assert(std::is_pointer<Ptr>::value, "Should be a pointer type");
    return ptr != nullptr;
  }
  
  class Object {};
  
  std::shared_ptr<Object> createObject() {
    auto created = std::make_shared<Object>();
    assert(not_null(created));
    return created;
  }
  ```
